ARG BASE_TAG="1.18.0-rolling-weekly"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/${BASE_IMAGE}:${BASE_TAG}

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
#WORKDIR $HOME
WORKDIR /home/kasm-default-profile


######### Customize Container Here ###########


COPY ./src/ubuntu/install/freecad $INST_SCRIPTS/freecad/
RUN bash $INST_SCRIPTS/freecad/install_freecad.sh  && rm -rf $INST_SCRIPTS/freecad/

COPY ./src/ubuntu/install/freecad/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

# Update the desktop environment to be optimized for a single application
#RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
#RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
#RUN apt-get remove -y xfce4-panel


######### End Customizations ###########


RUN chown 1000:0 $HOME

ENV HOME=/home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000